version: '3.9'


services:

  node1:
    build: ./NodeVM
    container_name: node1
    ports:
      - "4001:4001"
    networks:
      - cluster_network  



  node2:
    build: ./NodeVM
    container_name: node2
    ports:
      - "4002:4001"
    networks:
      - cluster_network 


  node3:
    build: ./NodeVM
    container_name: node3
    ports:
      - "4003:4001"
    networks:
      - cluster_network 

  bootstrap:
    build: ./Bootstrap
    container_name: bootstrapNode
    ports:
      - "4000:4000"
    depends_on:
      - node1
      - node2
      - node3
    networks:
      - cluster_network  

networks:
  cluster_network:      
